#!/usr/bin/env python

import argparse

parser = argparse.ArgumentParser()
parser.add_argument("arguments", nargs='+')
args = parser.parse_args().arguments

args = ' '.join(args).split("and")

npcs = []
for group in args:
    parts = group.split(" ")
    name = parts[1]
    number = int(parts[0]) if len(parts) > 2 else 1
    if name[-1] is 's' and number > 1:
        name = name[:-1]
    npcs.append((name, number))

print npcs
